### ISSUE TITLE
Word limit

### ISSUE THREAD

**Issue by huizhang001** [vivaxy/react-text-more-less#13]
Big Brother, can you add a word limit function? Pixels feel strange.

**Comment by vivaxy** [comment]
Please provide demo for more details.

**Comment by huizhang001** [comment]
额。。。就是能不能，以字数限制那个展开和收起，比如我要限制100字，才显示那个展开内容按钮。并不是根据高度。。。这样可以吗？

**Comment by vivaxy** [comment]
本组件的设计初衷是为了针对布局优化展示效果，因此这里限制的是组件高度。
如果是需要限制字数，解决方案的实现并不复杂，或可以使用其他组件，如 https://github.com/nkbt/react-collapse 等。

**Comment by huizhang001** [comment]
好，谢谢大佬
