### ISSUE TITLE
Do not collapse on user select

### ISSUE THREAD

**Issue by tabrez96** [vivaxy/react-text-more-less#3]
As a user, when the content/text is not collapsed it should be possible to select the text (for copy/paste purpose).

The text content should not collapse when the user has selected the text with the mouse. But currently, when I try to select the text, it collapses.

**Comment by tabrez96** [comment]
I have a workaround for this. In the function which is being called onClick, adding this will fix the issue,

```
var selection = window.getSelection();
if (!selection.toString()) {
 /* Actual code from function */
}
```

**Comment by vivaxy** [comment]
Thank you for you information. It's really an issue.
