### ISSUE TITLE
Toggle collapse is not working

### ISSUE THREAD

**Issue by sinchang** [vivaxy/react-text-more-less#73]
reproduce demo: https://codesandbox.io/s/serene-ramanujan-nn8e3?file=/src/App.js

@vivaxy could you have a look? 

thank you

**Comment by vivaxy** [comment]
Thank you for your feedback. Fixed in https://github.com/vivaxy/react-text-more-less/commit/465cf259c078e1b3135dabfedef2461118e0e893. Please try v0.4.2.

**Comment by sinchang** [comment]
verified. thanks
